### ISSUE TITLE
example of api aggregation with a controller for a custom resource

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/sample-apiserver#22]
this sample shows how to install a sample-apiserver, but doesnt show me how to use it. Here's my confusion:-
- how do i add sample crd controller which talks to the sample-apiserver to does custom validation ?
- i am guessing the answer is probably as simple as saying the same you would write any crd controleller with no aggregation, but just want to confirm.

once i have registered an apiservice to handle a custom resource, can i create a custom controller that watches the object using informers at the regular k8s apiserver, and expect everything to just work ?

**Comment by m1093782566** [comment]
+1 from me!

**Comment by m1093782566** [comment]
kindly ping @liggitt @sttts

**Comment by sttts** [comment]
> i am guessing the answer is probably as simple as saying the same you would write any crd controleller with no aggregation, but just want to confirm.

The provided resources are nothing special from the view of the controllers. Just use informers (created with code generation) and do the same you would do with native resources or CRDs.
