### ISSUE TITLE
Add docs for using custom subresources with aggregated apiserver

### ISSUE THREAD

**Issue by devdattakulkarni** [kubernetes/sample-apiserver#25]
This is helpful repository! However, it does not show how to create aggregated API server that supports custom subresources. If anyone comes here looking for that here is an example that might help:

https://github.com/cloud-ark/kubeprovenance

We have built this using sample-apiserver as the starting point. 

Here is a blog article that explains various approaches that we tried:

https://medium.com/@cloudark/our-journey-in-building-a-kubernetes-aggregated-api-server-29a4f9c1de22

Hopefully our trials and experiments will save others some time.

**Comment by nikhita** [comment]
@devdattakulkarni Can you update the title to `Add docs for using custom subresources with aggregated apiserver`?

**Comment by devdattakulkarni** [comment]
@nikhita Done.

**Comment by nikhita** [comment]
@devdattakulkarni thanks!
