### ISSUE TITLE
Unable to create storage backend

### ISSUE THREAD

**Issue by kargakis** [kubernetes/sample-apiserver#5]
Trying to run this with a cluster created by `hack/local-up-cluster` and stumbling upon the following issue when the api server pod runs.
```
$ kc logs -f deploy/wardle
I0508 18:36:00.059769       1 serving.go:270] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
F0508 18:36:00.213324       1 storage_decorator.go:61] Unable to create storage backend: config (&{ /registry/wardle.kubernetes.io []    false 0 0xc42008d9e0 0xc4202c0600}), err (etcdclient: no available endpoints)
```
@deads2k any ideas?

**Comment by kargakis** [comment]
cc: @sttts

**Comment by sttts** [comment]
@kargakis `etcdclient: no available endpoints` sounds like you forgot to pass the etcd servers in the command line

**Comment by deads2k** [comment]
We provide a sample set of resources: https://github.com/kubernetes/sample-apiserver/tree/master/artifacts/example, but they don't include a deployment.  Does your deployment match the example RC?

**Comment by kargakis** [comment]
Yeah, I am missing the etcd endpoint, thanks.

**Comment by kargakis** [comment]
@deads2k this example is running its own etcd - it would be nice to have an example where the main etcd is re-used.

**Comment by deads2k** [comment]
@kargakis It's possible, but its important to be careful with exposure of the etcd write key.  See this example https://github.com/openshift/origin/pull/13229

**Comment by geertschuring** [comment]
I've run into this problem and solved it by deleting the /etc/kubernetes directory on the host OS and reinstalling k8s.
