### ISSUE TITLE
Are non resource urls possible for a custom apiserver

### ISSUE THREAD

**Issue by maleck13** [kubernetes/sample-apiserver#9]
I am able to set up a new resource by setting up my own apiserver, but I would also like to add some non resource urls. Is this something that is possible currently? I have seen that you can add nonResourceURLs to a ClusterRole, but it is not clear how I would reach these routes if they were mounted on an apiserver.

**Comment by deads2k** [comment]
No, you cannot send traffic for nonresource urls since paths would potentially collide.
